### ISSUE TITLE
sofle zmk underglow

### ISSUE THREAD

**Issue by Domingo821** [gabrielkim13/zmk-config#1]
Hi Gabriel, hope all is well. This is not an actual issue. Just need help turning on the underglow. I'm having problems with the correct key sequence to turn it on. I'm fairly new to this but I had it working before. Thank you

**Comment by gabrielkim13** [comment]
Hi there, Domingo. How are you?

So sorry for the delay in responding; had a bit of a rushed week 😥.

I remember also having problems getting the underglow to work, but I can't recall what the problem was exactly.

To sum it up, I am currently running the following firmware + config:

- https://github.com/gabrielkim13/zmk/tree/sofle
  - At some point, I forked the official zmk repo and rebased [infused-kim's branch](https://github.com/infused-kim/zmk) to `main` in order to get some fixes; I think this was relevant to solving the problem...

- https://github.com/gabrielkim13/zmk-config-sofle
  - Turn on ext power*: Tab key, on layer 3
  - Toggle RGB underglow: Left encoder press, on layer 3

\* Pay attention to the ext power settings persistence interval (see [Power Management Behaviors](https://zmk.dev/docs/behaviors/power#behavior-binding)). I'm pretty sure the OLED display requires ext power to be up on the moment the keyboard is turned on, in order to be initialized correcly.

Here is a picture of the keyboard with both OLED display and RGB underglow working correctly:

![Sofle choc wireless](https://github.com/gabrielkim13/zmk-config/assets/68445851/b44642c7-e9e4-49a7-8583-df7eed2cf52d)

I am currently building the firmwares locally, by following ZMK's excellent docs:

- [Toolchain Setup](https://zmk.dev/docs/development/setup)
- [Building and Flashing](https://zmk.dev/docs/development/build-flash)

**Comment by Domingo821** [comment]
Hey Gabriel, all is well thank you. I appreciate you responding.  I too was crazy busy at work (4th quarter crunch). Oddly enough,  it resolved itself. I fully charged them and did every button sequence I could think of. It turned out that the fw needed a settings reset flash and  a reflash of your version like 3x. All is good now. Thank you fir your response! ![20231203_130338.jpg](https://github.com/gabrielkim13/zmk-config/assets/89996573/86d2988c-3312-43f5-ad53-6a8608bf7e41)

**Comment by gabrielkim13** [comment]
You're welcome, Domingo!

Nice to hear everything is working fine now!

Congrats on the keeboard, it looks awesome!
